enabled = true
name = "Mega Mix Thumbnail Manager"
description = "Compile in-game song thumbnails so that none of them will look broken."
version = "0.1.3"
date = "11.12.2022"
author = "joexyz"
dll = ["MegaMixThumbnailManager.dll"]
include = ["."]
