enabled = true
name = "Mega Mix Thumbnail Manager"
description = "Compile in-game song thumbnails so that none of them will look broken."
version = "0.2.0"
date = "01.02.2023"
author = "joexyz"
dll = ["MegaMixThumbnailManager.dll"]
include = ["."]
