enabled = true
name = "Mega Mix Thumbnail Manager"
description = "Compile in-game song thumbnails so that none of them will look broken."
version = "0.2.1"
date = "02.04.2023"
author = "joexyz"
dll = ["MegaMixThumbnailManager.dll"]
include = ["."]
